import { CarDeal } from './types';

const now = () => new Date();
const addHours = (h: number) => new Date(Date.now() + h * 3600 * 1000);
const addMinutes = (m: number) => new Date(Date.now() + m * 60 * 1000);

export const DEALS: CarDeal[] = [
  {
    id: '1',
    make: 'AUDI',
    model: 'RS6 AVANT',
    trim: 'PERFORMANCE',
    year: 2025,
    drive: 'AWD',
    type: 'LEASE',
    monthly: 1599,
    dueAtSigning: 7500,
    term: 36,
    milesPerYear: 7500,
    msrp: 130900,
    expiresAt: addHours(2),
    tier: 'GOLD',
    dropId: 'D-004',
    state: 'FL',
    city: 'Miami',
    slotsLeft: 1,
    zeroDeal: false,
    featured: true,
    carType: 'Sedan',
    accent: '#161616',
    stripe: 'linear-gradient(135deg, #161616 0%, #1e1e1e 100%)',
  },
  {
    id: '2',
    make: 'BMW',
    model: 'M3 COMPETITION',
    trim: 'XDRIVE',
    year: 2025,
    drive: 'AWD',
    type: 'LEASE',
    monthly: 1149,
    dueAtSigning: 0,
    term: 39,
    milesPerYear: 12000,
    msrp: 92800,
    expiresAt: addHours(4),
    tier: 'GOLD',
    dropId: 'D-009',
    state: 'GA',
    city: 'Atlanta',
    slotsLeft: 1,
    zeroDeal: true,
    carType: 'Sedan',
    accent: '#1a1a2e',
    stripe: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 100%)',
  },
  {
    id: '3',
    make: 'MERCEDES-BENZ',
    model: 'G-CLASS',
    trim: 'G 550',
    year: 2025,
    drive: '4WD',
    type: 'LEASE',
    monthly: 1899,
    dueAtSigning: 9999,
    term: 36,
    milesPerYear: 7500,
    msrp: 165400,
    expiresAt: addHours(6),
    tier: 'VERIFIED',
    dropId: 'D-001',
    state: 'CA',
    city: 'LA',
    slotsLeft: 1,
    zeroDeal: false,
    carType: 'SUV',
    accent: '#1c1c1c',
    stripe: 'linear-gradient(135deg, #1c1c1c 0%, #2a1a0e 100%)',
  },
  {
    id: '4',
    make: 'TESLA',
    model: 'MODEL 3',
    trim: 'PERFORMANCE',
    year: 2025,
    drive: 'AWD',
    type: 'LEASE',
    monthly: 549,
    dueAtSigning: 2999,
    term: 36,
    milesPerYear: 10000,
    msrp: 54990,
    expiresAt: addHours(9),
    tier: 'GOLD',
    dropId: 'D-012',
    state: 'TX',
    city: 'Houston',
    slotsLeft: 2,
    zeroDeal: false,
    carType: 'EV',
    accent: '#111827',
    stripe: 'linear-gradient(135deg, #111827 0%, #1f2937 100%)',
  },
  {
    id: '5',
    make: 'HYUNDAI',
    model: 'IONIQ 5 N',
    trim: 'AWD',
    year: 2025,
    drive: 'AWD',
    type: 'LEASE',
    monthly: 599,
    dueAtSigning: 3499,
    term: 36,
    milesPerYear: 10000,
    msrp: 67500,
    expiresAt: addHours(14),
    tier: 'GOLD',
    dropId: 'D-007',
    state: 'MI',
    city: 'Detroit',
    slotsLeft: null,
    zeroDeal: false,
    carType: 'EV',
    accent: '#0d1a2e',
    stripe: 'linear-gradient(135deg, #0d1a2e 0%, #0a1520 100%)',
  },
  {
    id: '6',
    make: 'PORSCHE',
    model: 'TAYCAN',
    trim: '4S',
    year: 2025,
    drive: 'AWD',
    type: 'LEASE',
    monthly: 899,
    dueAtSigning: 4999,
    term: 36,
    milesPerYear: 10000,
    msrp: 112400,
    expiresAt: addHours(18),
    tier: 'PLATINUM',
    dropId: 'D-005',
    state: 'AZ',
    city: 'Phoenix',
    slotsLeft: null,
    zeroDeal: true,
    carType: 'EV',
    accent: '#0a0e1a',
    stripe: 'linear-gradient(135deg, #0a0e1a 0%, #1a2030 100%)',
  },
  {
    id: '7',
    make: 'CADILLAC',
    model: 'ESCALADE-V',
    trim: 'SPORT PLATINUM',
    year: 2025,
    drive: 'AWD',
    type: 'LEASE',
    monthly: 1849,
    dueAtSigning: 8999,
    term: 36,
    milesPerYear: 10000,
    msrp: 168200,
    expiresAt: addHours(22),
    tier: 'GOLD',
    dropId: 'D-011',
    state: 'CO',
    city: 'Denver',
    slotsLeft: 1,
    zeroDeal: false,
    carType: 'SUV',
    accent: '#0d0a0a',
    stripe: 'linear-gradient(135deg, #0d0a0a 0%, #1a1010 100%)',
  },
  {
    id: '8',
    make: 'FORD',
    model: 'F-150 LIGHTNING',
    trim: 'FLASH',
    year: 2025,
    drive: 'AWD',
    type: 'LEASE',
    monthly: 449,
    dueAtSigning: 0,
    term: 36,
    milesPerYear: 10500,
    msrp: 67900,
    expiresAt: addHours(2),
    tier: 'VERIFIED',
    dropId: 'D-008',
    state: 'WA',
    city: 'Seattle',
    slotsLeft: null,
    zeroDeal: true,
    carType: 'Truck',
    accent: '#0a1018',
    stripe: 'linear-gradient(135deg, #0a1018 0%, #0d1520 100%)',
  },
  {
    id: '9',
    make: 'TOYOTA',
    model: 'TACOMA',
    trim: 'TRD PRO',
    year: 2025,
    drive: '4WD',
    type: 'LEASE',
    monthly: 619,
    dueAtSigning: 0,
    term: 36,
    milesPerYear: 12000,
    msrp: 64200,
    expiresAt: addHours(2),
    tier: 'PLATINUM',
    dropId: 'D-003',
    state: 'TX',
    city: 'DFW',
    slotsLeft: 4,
    zeroDeal: true,
    carType: 'Truck',
    accent: '#1a1200',
    stripe: 'linear-gradient(135deg, #1a1200 0%, #251a00 100%)',
  },
  {
    id: '10',
    make: 'LEXUS',
    model: 'RX 500h',
    trim: 'F SPORT',
    year: 2025,
    drive: 'AWD',
    type: 'LEASE',
    monthly: 799,
    dueAtSigning: 3999,
    term: 36,
    milesPerYear: 10000,
    msrp: 74900,
    expiresAt: addHours(48),
    tier: 'PLATINUM',
    dropId: 'D-010',
    state: 'CA',
    city: 'SF',
    slotsLeft: 3,
    zeroDeal: false,
    carType: 'SUV',
    accent: '#0a0f1e',
    stripe: 'linear-gradient(135deg, #0a0f1e 0%, #0e1830 100%)',
  },
  {
    id: '11',
    make: 'GENESIS',
    model: 'GV80',
    trim: '3.5T AWD',
    year: 2025,
    drive: 'AWD',
    type: 'LEASE',
    monthly: 699,
    dueAtSigning: 2500,
    term: 36,
    milesPerYear: 12000,
    msrp: 72500,
    expiresAt: addHours(36),
    tier: 'VERIFIED',
    dropId: 'D-006',
    state: 'IL',
    city: 'Chicago',
    slotsLeft: 5,
    zeroDeal: false,
    carType: 'SUV',
    accent: '#1a1a1a',
    stripe: 'linear-gradient(135deg, #1a1a1a 0%, #252525 100%)',
  },
  {
    id: '12',
    make: 'ALFA ROMEO',
    model: 'STELVIO',
    trim: 'QUADRIFOGLIO',
    year: 2025,
    drive: 'AWD',
    type: 'LEASE',
    monthly: 929,
    dueAtSigning: 3500,
    term: 36,
    milesPerYear: 10000,
    msrp: 88900,
    expiresAt: addMinutes(90),
    tier: 'GOLD',
    dropId: 'D-002',
    state: 'NY',
    city: 'NYC',
    slotsLeft: 2,
    zeroDeal: false,
    carType: 'SUV',
    accent: '#1a0505',
    stripe: 'linear-gradient(135deg, #1a0505 0%, #2a0a0a 100%)',
  },
];

export const TICKER_DEALS = DEALS.slice(0, 6);

export const STATS = {
  liveDrops: DEALS.length,
  zeroDown: DEALS.filter(d => d.zeroDeal).length,
  startingFrom: Math.min(...DEALS.map(d => d.monthly)),
};
